### ISSUE TITLE
Connect Wizmote without Wiz bulb

### ISSUE THREAD

**Issue by TheZoker** [jesserockz/wizmote-esphome#2]
Hi there,

Is there any way to connect the WizMote to the wifi without a Wiz wifi bulb already connected?
The Wiz app tells me, that in order to connect the remote to the wifi network, there needs to be at least one bulb already connected.

Thanks!

**Comment by jesserockz** [comment]
That is exactly what this repo provides if you use ESPHome and Home Assistant.
Kind of...

The remote never connects to anything, all it ever does is broadcasts an ESP-Now packet which the bulbs are listening for and they either act on those packets, or relay then to the WiZ cloud.

This ESPHome component does the same, listens for those packets and relays them to Home Assistant where you can use the blueprint to act on them with any light you have in Home Assistant.

**Comment by leovilela2** [comment]
Do you know how to get the MAC address for the wizmote?
