### ISSUE TITLE
!lambda tag not recognised. What am I doing wrong?

### ISSUE THREAD

**Issue by unwint** [jesserockz/wizmote-esphome#24]
Hi,
 I'm trying to get a Wizmote configured, I've got an ESP32 device connected. Added the blueprint and tried to add the lines of code to the configuration.yaml file but HA complains about the !lamda tag. I'm plainly missing something.

Sorry if I'm being stupid!

Thanks
Tom

"Configuration errors
Error loading /config/configuration.yaml: could not determine a constructor for the tag '!lambda'
in "/config/configuration.yaml", line 41, column 20"

**Comment by jesserockz** [comment]
Lambda is esphome only not HA yaml

**Comment by unwint** [comment]
Hi Jesse, thanks for responding but I have to say I don't understand the answer. Could you please pint me at some resourse that would help me understand.
I'm new to this.

Thanks
Tom

**Comment by jesserockz** [comment]
Your original description errors shows you are trying to write ESPHome yaml syntax into Home Assistant's configuration.yaml which is not where it goes. 
You need to add whatever lambda you are trying to add into your esphome device yaml.

You almost never need to touch home assistants main configuration.yaml these days.

**Comment by unwint** [comment]
Thank you. That helps. Made progress now. I do appreciate the help.
