### ISSUE TITLE
Button presses are missing intermittently 

### ISSUE THREAD

**Issue by pk802** [jesserockz/wizmote-esphome#8]
I am using Wizmote for while. When listening to events on HA it's missing few button presses intermittently. I have checked the ESP log and it's also not showing these button presses there. I am sharing a screenshot where 6 button presses were missed. There are no entries of these on ESP log also for the missed button presses. 

<img width="864" alt="Screenshot 2023-03-15 at 11 55 21 AM" src="https://user-images.githubusercontent.com/99890240/225224438-f9bba156-0349-4ed5-aa78-deb22dde50c0.png">

**Comment by andrewb2102** [comment]
having the same problem. any luck fixing it?

**Comment by kueblc** [comment]
Are you using an ESP8266 or ESP32?

It may be due to wifi radio power save mode. Try disabling power save in your ESPHome configuration:
```yaml
wifi:
  power_save_mode: none
```

**Comment by roynasser** [comment]
This should be in the readme!  I wasnt getting the blueprint to trigger, once I added the power save -> none, it works!
